### ISSUE TITLE
I am unable to launch the game as it says this is for version 1.18.1 but I am using the 1.18.2 version.

### ISSUE THREAD

**Issue by Skullkrushar2nd** [williambl/haema#124]
Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace mod 'Haema' (haema) 1.9.1+1.18.2 with any version that is compatible with:
		 - minecraft 1.18.2
Unmet dependency listing:
	 - Mod 'Haema' (haema) 1.9.1+1.18.2 requires version 1.18.1 of 'Minecraft' (minecraft), but only the wrong version is present: 1.18.2!
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by williambl** [comment]
oh my god i'm a dumbass

**Comment by williambl** [comment]
Fixed in 1.9.2+1.18.2.

**Comment by Skullkrushar2nd** [comment]
Thank you so much
